# Generated by Django 5.0.1 on 2025-02-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_customuser_referrals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='interests',
            field=models.CharField(blank=True, choices=[('sports', 'Sports'), ('music', 'Music'), ('travel', 'Travel'), ('technology', 'Technology'), ('art', 'Art'), ('gaming', 'Gaming'), ('fitness', 'Fitness'), ('business', 'Business'), ('science', 'Science'), ('fashion', 'Fashion')], max_length=100),
        ),
    ]
