# Generated by Django 5.0.1 on 2025-02-13 06:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_referralrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('description', models.TextField()),
                ('audience_type', models.CharField(choices=[('public', 'Public'), ('members_only', 'Members Only'), ('vip', 'VIP')], default='public', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_tickets', models.PositiveIntegerField()),
                ('attending_members', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
