# Generated by Django 5.0.1 on 2025-02-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_ask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='primary_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
