# Generated by Django 5.0.1 on 2025-02-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_customuser_primary_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
