# Generated by Django 5.0.1 on 2025-02-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_customuser_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_memeber',
            field=models.BooleanField(default=False),
        ),
    ]
