# Generated by Django 5.0.1 on 2025-02-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_attending',
            field=models.BooleanField(default=False),
        ),
    ]
